pipeline {
    agent any
    environment {

        PACKER_SH = '/opt/yandex-packer/packer build -color=false'
    }
    stages {
        stage('Core') {
            steps {
                sh label: '', script: "${env.PACKER_SH} ./jenkins-packer/packer/base.json"
            }
        }
        stage('Role-Based') {
            steps {
                parallel(
                    nginx: {
                        sh label: '', script: "${env.PACKER_SH} ./jenkins-packer/packer/nginx.json"
                    },
                    django: {
                        sh label: '', script: "${env.PACKER_SH} ./jenkins-packer/packer/django.json" 
                    }
                )
            }
        }
    }
}

